/**
 * Component categorization shared between list_components and extraction script
 */

export const REACT_COMPONENT_CATEGORIES = {
  'Data Display': ['AnalyticalTable', 'AnalyticalCardHeader', 'ObjectStatus', 'NumericSideIndicator'],
  'Layouts & Floorplans': [
    'ObjectPage',
    'ObjectPageSection',
    'ObjectPageSubSection',
    'ObjectPageTitle',
    'ObjectPageHeader',
    'ObjectPageAnchorBar',
    'FlexBox',
    'Grid',
    'ResponsiveGridLayout',
    'SplitterLayout',
    'SplitterElement',
    'Splitter',
    'ThemeProvider',
    'FilterBar',
  ],
  Inputs: ['FilterGroupItem', 'VariantManagement', 'VariantItem', 'MessageViewButton'],
  'Modals & Popovers': ['MessageBox', 'ActionSheet', 'SelectDialog'],
  'User Feedback': ['MessageView', 'MessageItem', 'Modals'],
};

export const WEB_COMPONENT_CATEGORIES = {
  'Data Display': [
    'Avatar',
    'AvatarBadge',
    'AvatarGroup',
    'Card',
    'CardHeader',
    'ColorPalette',
    'ColorPaletteItem',
    'ExpandableText',
    'Icon',
    'Label',
    'Link',
    'List',
    'ListItemStandard',
    'ListItemCustom',
    'ListItemGroup',
    'MessageStrip',
    'NotificationList',
    'NotificationListItem',
    'NotificationListGroupItem',
    'ProgressIndicator',
    'Table',
    'TableRow',
    'TableRowAction',
    'TableRowActionNavigation',
    'TableCell',
    'TableHeaderRow',
    'TableHeaderCell',
    'TableHeaderCellActionAI',
    'TableSelection',
    'TableSelectionSingle',
    'TableSelectionMulti',
    'TableVirtualizer',
    'TableGrowing',
    'Tag',
    'Text',
    'Timeline',
    'TimelineItem',
    'TimelineGroupItem',
    'Title',
    'Tree',
    'TreeItem',
    'TreeItemCustom',
  ],
  Inputs: [
    'Button',
    'ButtonBadge',
    'Calendar',
    'CalendarDate',
    'CalendarDateRange',
    'CalendarLegend',
    'CalendarLegendItem',
    'CheckBox',
    'ColorPicker',
    'ComboBox',
    'ComboBoxItem',
    'ComboBoxItemGroup',
    'DatePicker',
    'DateRangePicker',
    'DateTimePicker',
    'DynamicDateRange',
    'FileUploader',
    'Input',
    'MultiComboBox',
    'MultiComboBoxItem',
    'MultiComboBoxItemGroup',
    'MultiInput',
    'ProductSwitch',
    'ProductSwitchItem',
    'RadioButton',
    'RangeSlider',
    'RatingIndicator',
    'Search',
    'SearchScope',
    'SearchItem',
    'SearchItemGroup',
    'SearchItemShowMore',
    'SearchMessageArea',
    'SegmentedButton',
    'SegmentedButtonItem',
    'Select',
    'Option',
    'OptionCustom',
    'Slider',
    'SpecialCalendarDate',
    'SplitButton',
    'StepInput',
    'SuggestionItem',
    'SuggestionItemCustom',
    'SuggestionItemGroup',
    'Switch',
    'TextArea',
    'TimePicker',
    'ToggleButton',
    'Token',
    'Tokenizer',
    'UploadCollection',
    'UploadCollectionItem',
  ],
  'Layouts & Floorplans': [
    'Bar',
    'Breadcrumbs',
    'BreadcrumbsItem',
    'Carousel',
    'DynamicPage',
    'DynamicPageHeader',
    'DynamicPageTitle',
    'DynamicSideContent',
    'FlexibleColumnLayout',
    'Form',
    'FormGroup',
    'FormItem',
    'MediaGallery',
    'MediaGalleryItem',
    'NavigationLayout',
    'Page',
    'Panel',
    'ShellBar',
    'ShellBarItem',
    'ShellBarSpacer',
    'ShellBarBranding',
    'ShellBarSearch',
    'SideNavigation',
    'SideNavigationGroup',
    'SideNavigationItem',
    'SideNavigationSubItem',
    'Tab',
    'TabContainer',
    'TabSeparator',
    'Toolbar',
    'ToolbarButton',
    'ToolbarItem',
    'ToolbarSelect',
    'ToolbarSelectOption',
    'ToolbarSeparator',
    'ToolbarSpacer',
    'Wizard',
    'WizardStep',
  ],
  'Modals & Popovers': [
    'BarcodeScannerDialog',
    'ColorPalettePopover',
    'Dialog',
    'Menu',
    'MenuItem',
    'MenuItemGroup',
    'MenuSeparator',
    'Popover',
    'ResponsivePopover',
    'Toast',
    'UserMenu',
    'UserMenuAccount',
    'UserMenuItem',
    'UserMenuItemGroup',
    'UserSettingsAccountView',
    'UserSettingsAppearanceView',
    'UserSettingsAppearanceViewGroup',
    'UserSettingsAppearanceViewItem',
    'UserSettingsDialog',
    'UserSettingsItem',
    'UserSettingsView',
    'ViewSettingsDialog',
    'FilterItem',
    'FilterItemOption',
    'GroupItem',
    'SortItem',
  ],
  'User Feedback': ['BusyIndicator', 'IllustratedMessage'],
};

export const CHART_CATEGORIES = {
  Charts: [
    'BarChart',
    'LineChart',
    'ColumnChart',
    'PieChart',
    'DonutChart',
    'RadialChart',
    'RadarChart',
    'ScatterChart',
    'ComposedChart',
    'BulletChart',
    'ColumnChartWithTrend',
    'TimelineChart',
  ],
};

export const AI_CATEGORIES = {
  'AI Components': ['Button', 'ButtonState', 'Input', 'PromptInput', 'TextArea'],
};
