name: 'Build w/ React18 & 19'

on:
  workflow_call:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: ['18', '19']
    env:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install
        run: yarn install --immutable

      - name: Install 18
        if: ${{ matrix.react == '18' }}
        run: |
          yarn add "@types/react@18" "@types/react-dom@18" --dev
          yarn add react@18 react-dom@18

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-${{ matrix.react }}
          path: packages/*/dist
