name: 'chromatic'

on: push

jobs:
  chromatic:
    if: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[ci chromatic]') }}
    runs-on: ubuntu-latest
    env:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish to Chromatic
        uses: chromaui/action@4ffe736a2a8262ea28067ff05a13b635ba31ec05 # v13.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build:storybook'
          skip: 'dependabot/**'
        env:
          STORYBOOK_ENV: chromatic
          NODE_OPTIONS: '--max-old-space-size=4096'
